# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                    # Nombre de pages à afficher dans la pagination
    default_options:
        page_name: page               # Nom du paramètre pour la page actuelle
        sort_field_name: sort         # Nom du paramètre pour trier les colonnes
        sort_direction_name: direction # Nom du paramètre pour la direction de tri
        filter_field_name: filterField  # Nom du paramètre pour filtrer les colonnes
        filter_value_name: filterValue  # Nom du paramètre pour la valeur du filtre
    template:
        pagination: '@KnpPaginator/Pagination/tailwindcss_pagination.html.twig'     # sliding pagination controls template
        rel_links: '@KnpPaginator/Pagination/rel_links.html.twig'     # <link rel=...> tags template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

